### ISSUE TITLE
Upload/download rate limiting

### ISSUE THREAD

**Issue by bajtos** [filecoin-saturn/L2-node#47]
In addition to max cache size, we should also allow the user to configure upload and download rate limits. Without this feature, a Saturn L2 node running in a home or corporate network can cause undesirable performance degradation for other users.

This configuration can have granularity in KB/s if there is any value in L2 nodes with up/down speeds lower than 1MB/s. The granularity can be in MB/s otherwise.

Example: configuration screen from OneDrive, a DropBox alternative:

<img width="652" alt="Screenshot 2022-08-01 at 16 57 58" src="https://user-images.githubusercontent.com/1140553/182187039-aa60040f-3cd0-439f-9687-88b5cef10a17.png">

**Comment by gruns** [comment]
two types of bw limitation related configurations come to mind:

1. real-time bw limits, eg 100kbps upload maximum
2. optionally, a maximum amount of bw transferred in a given time period. eg dont upload more than 100GB per week or per month

for prior art, we can look at what various bittorrent clients offer configuration wise to control bw usage — both real-time and in aggregate (ie X GB used monthly)

both of these settings are a better fit in the station’s configuration, not the saturn module's. imagine when there are 4 station modules that all use download and/or upload bandwidth. UX wise, the user likely wants to limit the total bw usage of all station apps, not each individually, to:

1. avoid impacting their personal use of the device (real-time limits)
2. not blow through their monthly bw allotment (total bw transferred in a given time period limit)

we want to avoid multi-module coordination and use techniques like OSs do to limit the bw usage of an app at the app level

all that said above, the ideal UX for real-time bw download/upload rate limitation is for station to automatically detect congestion and throttle back all station activity. this avoids the user having to think about setting a limit and always achieves maximum performance/output for saturn while simultaneously preserving the UX. aka station 'just works'

priority wise, i view bw limiting configuration as a non-required feature. that is, i am totally ok launching l2s without any bandwidth limiting configuration and adding it later. i dont see this as a blocker for launching l2s and see it as something we’d add after launch

**Comment by bajtos** [comment]
> these settings are a better fit in the station’s configuration, not the saturn module's

Great idea! I opened https://github.com/filecoin-project/filecoin-station/issues/66 to discuss this feature in the context of the Station.
