### ISSUE TITLE
Fetch /nodes/nearby from orchestrator

### ISSUE THREAD

**Issue by juliangruber** [filecoin-saturn/L2-node#49]
When the L2 node boots up, it will ask the orchestrator for a list of geo-located L1 nodes.
Orchestrator will reply with a JSON array of IP addresses of L1 nodes situated in the same region as the requesting L2 node.

See last paragraph in https://www.notion.so/pl-strflt/Elaborate-L1-L2-MVP-flow-and-mechanics-793d381d04974a6b903078bf10e72b2a for the orchestrator address and a  sample response from this API.

The IP address/DNS of the orchestrator will be added as a configuration param in the L2 binary.

For https://github.com/filecoin-saturn/L2-node/issues/48.

**Comment by aarshkshah1992** [comment]
This is now done.
