### ISSUE TITLE
Record, store and expose the number of retrievals handled

### ISSUE THREAD

**Issue by bajtos** [filecoin-saturn/L2-node#52]
In Filecoin Station, we want to display the total number of retrievals (jobs) handled by the Station. To do that, we need the Saturn L2 Node to:
- record this number
- preserve it across restarts
- return the number in the REST API response

/cc @juliangruber

**Comment by aarshkshah1992** [comment]
Closed by https://github.com/filecoin-saturn/L2-node/pull/59.
