### ISSUE TITLE
Problem consultation: Node network connection error

### ISSUE THREAD

**Issue by gitsrc** [filecoin-saturn/L2-node#89]
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/34047788/194739848-48913ff5-62b9-48ed-96eb-d6bfcfbb9832.png">

I tried to run L2-node, using the environment variable L1_DISCOVERY_API_URL=https://orchestrator.strn.pl/nodes/nearby, the error in the picture appeared, how to solve it, thank you very much.

**Comment by gitsrc** [comment]
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/34047788/194740177-2abc50bb-e97e-4d53-bfd5-57db7b610059.png">

I changed a line of code and was able to ignore the error for the time being.

**Comment by juliangruber** [comment]
@gitsrc could you please share how you resolved this issue?

**Comment by juliangruber** [comment]
cc @aarshkshah1992
