### ISSUE TITLE
Cannot connect to Saturn testate

### ISSUE THREAD

**Issue by bajtos** [filecoin-saturn/L2-node#93]
Saturn L2 nodes cannot connect to L1 nodes due to certificate hostname mismatch.

I am able to reproduce the error by running Saturn L2 directly from the latest `main`:

```
$ FIL_WALLET_ADDRESS=f16m[...] go run ./cmd/saturn-l2/
[...] 
2022-11-15T09:47:15.983+0100	ERROR	l1-interop	l1interop/l1sseclient.go:145	
  failed to send register request to l1; will backoff and retry	
  {"l1": "51.75.68.126", "err": "Get \"https://51.75.68.126/register/8482aa44-0337-401b-bf65-17fc167e3692\": x509: "strn-test.pl" certificate name does not match input"}
```

See this thread in Filecoin Slack for more details: https://filecoinproject.slack.com/archives/C03S6LXSRB8/p1668250304814869

If I am reading the logs correctly, the problem is that the L1 node is presenting a certificate for a different hostname than L2 expected.

```
l1interop/l1sseclient.go:145    failed to send register request to l1; will backoff and retry
   {"l1": "145.239.92.38", "err": "Get \"https://145.239.92.38/register/29e6d8c4-be74-4d3c-876d-a0cd6e657739\": x509: certificate is valid for strn-test.pl, core.strn-test.pl, rings.strn-test.pl, not saturn-test.network"}
```

My understanding:
- Saturn L2 connects to the L1 using the hostname `saturn-test.network`. 
- L1 presents a certificate for different hostnames (`strn-test.pl`, `core.strn-test.pl`, `rings.strn-test.pl`). 
- As a result, L2 rejects the connection.

**Comment by juliangruber** [comment]
https://github.com/filecoin-saturn/L2-node/pull/94
